name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64



      - name: Run Maven Test
        run: mvn test

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact
        with:
          name: checkstyle.xml
          path: target/checkstyle-result.xml

      - name: Jacoco Report
        uses: actions/upload-artifact
        with:
          name: jacoco.xml
          path: target/site/jacoco/jacoco.xml
